INSERT INTO countries(id, name) VALUES(1, 'Colombia')
INSERT INTO provinces(id, name, country_id) VALUES(1, 'Amazonas', 1);
INSERT INTO provinces(id, name, country_id) VALUES(2, 'Antioquia', 1);
INSERT INTO provinces(id, name, country_id) VALUES(3, 'Arauca', 1);
INSERT INTO provinces(id, name, country_id) VALUES(4, 'Atlántico', 1);
INSERT INTO provinces(id, name, country_id) VALUES(5, 'Bolívar', 1);
INSERT INTO provinces(id, name, country_id) VALUES(6, 'Boyacá', 1);
INSERT INTO provinces(id, name, country_id) VALUES(7, 'Caldas', 1);
INSERT INTO provinces(id, name, country_id) VALUES(8, 'Caquetá', 1);
INSERT INTO provinces(id, name, country_id) VALUES(9, 'Casanare', 1);
INSERT INTO provinces(id, name, country_id) VALUES(10, 'Cauca', 1);
INSERT INTO provinces(id, name, country_id) VALUES(11, 'Cesar', 1);
INSERT INTO provinces(id, name, country_id) VALUES(12, 'Chocó', 1);
INSERT INTO provinces(id, name, country_id) VALUES(13, 'Córdoba', 1);
INSERT INTO provinces(id, name, country_id) VALUES(14, 'Cundinamarca', 1);
INSERT INTO provinces(id, name, country_id) VALUES(15, 'Guainía', 1);
INSERT INTO provinces(id, name, country_id) VALUES(16, 'Guaviare', 1);
INSERT INTO provinces(id, name, country_id) VALUES(17, 'Huila', 1);
INSERT INTO provinces(id, name, country_id) VALUES(18, 'La Guajira', 1);
INSERT INTO provinces(id, name, country_id) VALUES(19, 'Magdalena', 1);
INSERT INTO provinces(id, name, country_id) VALUES(20, 'Meta', 1);
INSERT INTO provinces(id, name, country_id) VALUES(21, 'Nariño', 1);
INSERT INTO provinces(id, name, country_id) VALUES(22, 'Norte de Santander', 1);
INSERT INTO provinces(id, name, country_id) VALUES(23, 'Putumayo', 1);
INSERT INTO provinces(id, name, country_id) VALUES(24, 'Quindío', 1);
INSERT INTO provinces(id, name, country_id) VALUES(25, 'Risaralda', 1);
INSERT INTO provinces(id, name, country_id) VALUES(26, 'San Andrés y Providencia', 1);
INSERT INTO provinces(id, name, country_id) VALUES(27, 'Santander', 1);
INSERT INTO provinces(id, name, country_id) VALUES(28, 'Sucre', 1);
INSERT INTO provinces(id, name, country_id) VALUES(29, 'Tolima', 1);
INSERT INTO provinces(id, name, country_id) VALUES(30, 'Valle del Cauca', 1);
INSERT INTO provinces(id, name, country_id) VALUES(31, 'Vaupés', 1);
INSERT INTO provinces(id, name, country_id) VALUES(32, 'Vichada', 1);
INSERT INTO countries(id, name) VALUES(2, 'Argentina')
INSERT INTO provinces(id, name, country_id) VALUES(33, 'Buenos Aires', 2);
INSERT INTO provinces(id, name, country_id) VALUES(34, 'Catamarca', 2);
INSERT INTO provinces(id, name, country_id) VALUES(35, 'Chaco', 2);
INSERT INTO provinces(id, name, country_id) VALUES(36, 'Chubut', 2);
INSERT INTO provinces(id, name, country_id) VALUES(37, 'Córdova', 2);
INSERT INTO provinces(id, name, country_id) VALUES(38, 'Corrientes', 2);
INSERT INTO provinces(id, name, country_id) VALUES(39, 'Entre Ríos', 2);
INSERT INTO provinces(id, name, country_id) VALUES(40, 'Formosa', 2);
INSERT INTO provinces(id, name, country_id) VALUES(41, 'Jujuy', 2);
INSERT INTO provinces(id, name, country_id) VALUES(42, 'La Pampa', 2);
INSERT INTO provinces(id, name, country_id) VALUES(43, 'La Rioja', 2);
INSERT INTO provinces(id, name, country_id) VALUES(44, 'Mendoza', 2);
INSERT INTO provinces(id, name, country_id) VALUES(45, 'Misiones', 2);
INSERT INTO provinces(id, name, country_id) VALUES(46, 'Neuquén', 2);
INSERT INTO provinces(id, name, country_id) VALUES(47, 'Río Negro', 2);
INSERT INTO provinces(id, name, country_id) VALUES(48, 'Salta', 2);
INSERT INTO provinces(id, name, country_id) VALUES(49, 'San Juan', 2);
INSERT INTO provinces(id, name, country_id) VALUES(50, 'San Luis', 2);
INSERT INTO provinces(id, name, country_id) VALUES(51, 'Santa Cruz', 2);
INSERT INTO provinces(id, name, country_id) VALUES(52, 'Santa Fe', 2);
INSERT INTO provinces(id, name, country_id) VALUES(53, 'Santiago del Estero', 2);
INSERT INTO provinces(id, name, country_id) VALUES(54, 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 2);
INSERT INTO provinces(id, name, country_id) VALUES(55, 'Tucumán', 2);
INSERT INTO countries(id, name) VALUES(3, 'Chile')
INSERT INTO provinces(id, name, country_id) VALUES(56, 'Arica', 3);
INSERT INTO provinces(id, name, country_id) VALUES(57, 'Parinacota', 3);
INSERT INTO provinces(id, name, country_id) VALUES(58, 'Iquique', 3);
INSERT INTO provinces(id, name, country_id) VALUES(59, 'Tamarugal', 3);
INSERT INTO provinces(id, name, country_id) VALUES(60, 'Tocopilla', 3);
INSERT INTO provinces(id, name, country_id) VALUES(61, 'El Loa', 3);
INSERT INTO provinces(id, name, country_id) VALUES(62, 'Antofagasta', 3);
INSERT INTO provinces(id, name, country_id) VALUES(63, 'Chañaral', 3);
INSERT INTO provinces(id, name, country_id) VALUES(64, 'Copiapó', 3);
INSERT INTO provinces(id, name, country_id) VALUES(65, 'Huasco', 3);
INSERT INTO provinces(id, name, country_id) VALUES(66, 'Elqui', 3);
INSERT INTO provinces(id, name, country_id) VALUES(67, 'Limarí', 3);
INSERT INTO provinces(id, name, country_id) VALUES(68, 'Choapa', 3);
INSERT INTO provinces(id, name, country_id) VALUES(69, 'Petorca', 3);
INSERT INTO provinces(id, name, country_id) VALUES(70, 'Los Andes', 3);
INSERT INTO provinces(id, name, country_id) VALUES(71, 'San Felipe de Aconcagua', 3);
INSERT INTO provinces(id, name, country_id) VALUES(72, 'Quillota', 3);
INSERT INTO provinces(id, name, country_id) VALUES(73, 'Valparaíso', 3);
INSERT INTO provinces(id, name, country_id) VALUES(74, 'San Antonio', 3);
INSERT INTO provinces(id, name, country_id) VALUES(75, 'Isla de Pascua', 3);
INSERT INTO provinces(id, name, country_id) VALUES(76, 'Marga Marga', 3);
INSERT INTO provinces(id, name, country_id) VALUES(77, 'Chacabuco', 3);
INSERT INTO provinces(id, name, country_id) VALUES(78, 'Santiago', 3);
INSERT INTO provinces(id, name, country_id) VALUES(79, 'Cordillera', 3);
INSERT INTO provinces(id, name, country_id) VALUES(80, 'Maipo', 3);
INSERT INTO provinces(id, name, country_id) VALUES(81, 'Melipilla', 3);
INSERT INTO provinces(id, name, country_id) VALUES(82, 'Talagante', 3);
INSERT INTO provinces(id, name, country_id) VALUES(83, 'Cachapoal', 3);
INSERT INTO provinces(id, name, country_id) VALUES(84, 'Colchagua', 3);
INSERT INTO provinces(id, name, country_id) VALUES(85, 'Caro', 3);
INSERT INTO provinces(id, name, country_id) VALUES(86, 'Curicó', 3);
INSERT INTO provinces(id, name, country_id) VALUES(87, 'Talca', 3);
INSERT INTO provinces(id, name, country_id) VALUES(88, 'Linares', 3);
INSERT INTO provinces(id, name, country_id) VALUES(89, 'Cauquenes', 3);
INSERT INTO provinces(id, name, country_id) VALUES(90, 'Diguillín', 3);
INSERT INTO provinces(id, name, country_id) VALUES(91, 'Itata', 3);
INSERT INTO provinces(id, name, country_id) VALUES(92, 'Punilla', 3);
INSERT INTO provinces(id, name, country_id) VALUES(93, 'Biobío', 3);
INSERT INTO provinces(id, name, country_id) VALUES(94, 'Concepción', 3);
INSERT INTO provinces(id, name, country_id) VALUES(95, 'Arauco', 3);
INSERT INTO provinces(id, name, country_id) VALUES(96, 'Malleco', 3);
INSERT INTO provinces(id, name, country_id) VALUES(97, 'Cautín', 3);
INSERT INTO provinces(id, name, country_id) VALUES(98, 'Valdivia', 3);
INSERT INTO provinces(id, name, country_id) VALUES(99, 'Ranco', 3);
INSERT INTO provinces(id, name, country_id) VALUES(100, 'Osorno', 3);
INSERT INTO provinces(id, name, country_id) VALUES(101, 'Llanquihue', 3);
INSERT INTO provinces(id, name, country_id) VALUES(102, 'Chiloé', 3);
INSERT INTO provinces(id, name, country_id) VALUES(103, 'Palena', 3);
INSERT INTO provinces(id, name, country_id) VALUES(104, 'Coyhaique', 3);
INSERT INTO provinces(id, name, country_id) VALUES(105, 'Aysén', 3);
INSERT INTO provinces(id, name, country_id) VALUES(106, 'General Carrera', 3);
INSERT INTO provinces(id, name, country_id) VALUES(107, 'Capitán Prat', 3);
INSERT INTO provinces(id, name, country_id) VALUES(108, 'Última Esperanza', 3);
INSERT INTO provinces(id, name, country_id) VALUES(109, 'Magallanes', 3);
INSERT INTO provinces(id, name, country_id) VALUES(110, 'Tierra del Fuego', 3);
INSERT INTO provinces(id, name, country_id) VALUES(111, 'Antártica Chilena', 3);

INSERT INTO users(id, first_name, last_name, email, phone) VALUES(1, 'Jhan', 'Ca', 'jhan@gmail.com', "32516136513")
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(2, 'Alice', 'Smith', 'alice.smith@example.com', '1234567890');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(3, 'Bob', 'Johnson', 'bob.johnson@example.com', '0987654321');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(4, 'Charlie', 'Brown', 'charlie.brown@example.com', '1112223333');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(5, 'Diana', 'Davis', 'diana.davis@example.com', '4445556666');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(6, 'Eve', 'Miller', 'eve.miller@example.com', '7778889999');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(7, 'Frank', 'Wilson', 'frank.wilson@example.com', '3332221111');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(8, 'Grace', 'Moore', 'grace.moore@example.com', '6665554444');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(9, 'Hank', 'Taylor', 'hank.taylor@example.com', '9998887777');
INSERT INTO users(id, first_name, last_name, email, phone) VALUES(10, 'Ivy', 'Anderson', 'ivy.anderson@example.com', '2223334445');

